services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: visitor-sql-express
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Your_password123"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - visitor-sql-data:/var/opt/mssql

volumes:
  visitor-sql-data:
